# Generated by Django 4.0.4 on 2022-05-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='nairobi', max_length=100)),
                ('weather', models.CharField(default='hot', max_length=100)),
            ],
        ),
    ]
