# Generated by Django 4.0.4 on 2022-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='experience',
            field=models.CharField(default='i love it', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='region',
            field=models.CharField(default='Central', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='Tsavo', max_length=100),
        ),
    ]
