# Generated by Django 4.0.4 on 2022-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_feature_experience_alter_feature_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='location',
            new_name='nearby_town',
        ),
        migrations.AlterField(
            model_name='feature',
            name='weather',
            field=models.CharField(default='nairobi', max_length=100),
        ),
    ]
