# Generated by Django 4.0.4 on 2022-06-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_location_feature_nearby_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='weather',
        ),
        migrations.AddField(
            model_name='feature',
            name='degree_celcius',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='weather_text',
            field=models.CharField(blank=True, default='warm', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='weather_url',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='feature',
            name='experience',
            field=models.CharField(default='i loved it', max_length=100),
        ),
    ]
