# Generated by Django 4.0.4 on 2022-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_feature_weather_feature_degree_celcius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image_url',
            field=models.URLField(default='//cdn.weatherapi.com/weather/64x64/day/116.png', max_length=30),
        ),
    ]
