# Generated by Django 4.0.4 on 2022-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feature_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='experience',
            field=models.CharField(default='i loved it', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image_url',
            field=models.URLField(default='//cdn.weatherapi.com/weather/64x64/day/116.png', max_length=256),
        ),
        migrations.AlterField(
            model_name='feature',
            name='nearby_town',
            field=models.CharField(default='nairobi', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='region',
            field=models.CharField(default='Central', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='Tsavo', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='weather_text',
            field=models.CharField(blank=True, default='warm', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='weather_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
