# Generated by Django 4.0.4 on 2022-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_feature_experience_alter_feature_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image_url',
            field=models.URLField(default='//cdn.weatherapi.com/weather/64x64/day/116.png'),
        ),
    ]
