# Generated by Django 4.0.4 on 2022-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_feature_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image_url',
            field=models.CharField(default='//cdn.weatherapi.com/weather/64x64/day/116.png', max_length=255),
        ),
    ]
